#!/bin/sh
INSTALLDIR='/var/tmp/nodevalet'
INFODIR='/var/tmp/nvtemp'
PROJECT=`cat $INFODIR/vpscoin.info`
MNS=`cat $INFODIR/vps.number.info`
LOGFILE='/var/tmp/nodevalet/logs/checkdaemon.log'

## Black        0;30     Dark Gray     1;30
## Red          0;31     Light Red     1;31
## Green        0;32     Light Green   1;32
## Brown/Orange 0;33     Yellow        1;33
## Blue         0;34     Light Blue    1;34
## Purple       0;35     Light Purple  1;35
## Cyan         0;36     Light Cyan    1;36
## Light Gray   0;37     White         1;37

color1='\033[1;31m'  # light red
color2='\033[0;31m'  # red
color3='\033[1;34m'  # light blue
color4='\033[0;33m'  # green
color5='\033[0;32m'  # light green
color6='\033[0;34m'  # blue
color7='\033[1;35m'  # light purple
color8='\033[0;35m'  # purple
color9='\033[1;36m'  # light cyan
color10='\033[0;36m'  # cyan
color11='\033[0;37m'  # light grey
color12='\033[1;37m'  # white
color13='\033[0;33m'  # brown
color14='\033[1;33m'  # yellow
nocolor='\033[0m'    # no color

#nodecount -- problemmatic for masternodes not named exactly right
# total=`ps aux | grep -i ${PROJECT}d | wc -l`
# nodes=`expr $total - 1`

# AKcryptoGUY's mod
printf " ${color5} █████████████████████████████${color1}  You've logged into a `echo "${PROJECT}"` Masternode${nocolor}\n"
printf " ${color5} █                           █${color9}  No currency is stored on this server.${nocolor}\n"
printf " ${color5} █ ${color12}   ███╗   ██╗██╗   ██╗  ${color5}  █${nocolor}\n"
printf " ${color5} █ ${color12}   ████╗  ██║██║   ██║  ${color5}  █${color14}  -------- General Information --------\n"
printf " ${color5} █ ${color12}   ██╔██╗ ██║██║   ██║  ${color5}  █${color11}\n"
printf " ${color5} █ ${color12}   ██║╚██╗██║╚██╗ ██╔╝  ${color5}  █${color11}  Hostname:${color12} $(hostname)\n"
printf " ${color5} █ ${color12}   ██║ ╚████║ ╚████╔╝   ${color5}  █${color11}  Version: `lsb_release -s -d`${nocolor}\n"
printf " ${color5} █ ${color12}   ╚═╝  ╚═══╝  ╚═══╝    ${color5}  █${color11}  `uname -srmo`${nocolor}\n"
printf " ${color5} █                           █${color11}\n"
printf " ${color5} █ ${color14}  --> NodeValet.io <-- ${color5}   █${color11}  Masternodes on this server: ${color7} --> ${MNS} <--${nocolor}\n"
printf " ${color5} █ ${color14}Your only choice for five${color5} █${color11}  External IP: ${color12}`/usr/bin/wget -q -O - http://ipv4.icanhazip.com/ | /usr/bin/tail` \n"
printf " ${color5} █  ${color14}minute masternode setup${color5}  █${nocolor}\n"
printf " ${color5} █                           █${color14}  `date +"%A, %e %B %Y, %r"`${nocolor}\n"
printf " ${color5} █████████████████████████████${color1}  * Uptime: `/usr/bin/uptime -p` *${nocolor}\n"

